[background]
path = "/opt/grant-ritchie-x1w_Q78xNEY-unsplash.jpg"
fit = "Fill"

# The entries defined in this section will be passed to the session as environment variables when it is started
[env]

[GTK]
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Adwaita"

# Font name and size
font_name = "JetBrainsMono Nerd Font Mono 11"

# Icon theme name
icon_theme_name = "Dracula"

# GTK theme name
theme_name = "Dracula"

[commands]
# The command used to reboot the system
reboot = [ "systemctl", "reboot" ]

# The command used to shut down the system
poweroff = [ "systemctl", "poweroff" ]

[appearance]
greeting_msg = "Welcome"
