set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# Change leader key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Change pane split controls to \ & -
bind \\ split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# Ensure current path is kept on new windows
bind c new-window -c "#{pane_current_path}"

# vim-like switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Resize panes
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

# Increase history limit
set-option -g history-limit 5000

# Reload environment configuration
bind R run-shell "steward sync remote &> /dev/null" \; display "reloaded dotfiles"

# Quick source configuration
bind r source-file ~/.tmux.conf \; display "reloaded configuration"
