[background]
path = "/opt/ign_mountains.png"
fit = "Fill"

# The entries defined in this section will be passed to the session as environment variables when it is started
[env]

[GTK]
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "elementary"

# Font name and size
font_name = "MesloLGS NF 14"

# Icon theme name
icon_theme_name = "Breeze Dark"

# GTK theme name
theme_name = "Nordic"

[commands]
# The command used to reboot the system
reboot = [ "systemctl", "reboot" ]

# The command used to shut down the system
poweroff = [ "systemctl", "poweroff" ]

[appearance]
greeting_msg = "Welcome"
