#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar top &
feh --no-fehbg --bg-fill --randomize $HOME/.config/polybar/wallpapers/* &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -eDP-1 d I II III IV

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          20

